### ISSUE TITLE
Green line at the bottom

### ISSUE THREAD

**Issue by theChaosCoder** [sekrit-twc/znedi3#11]
```
clip = core.colorbars.ColorBars(format=vs.YUV444P10)
clip = clip.resize.Point(format=vs.YUV420P8)
clip = clip.std.CropRel( left=138, top=0, right=138, bottom=0)
clip = clip.resize.Point(1920, 1206)
clip = clip.nnedi3.nnedi3(field=1)
```
colorbars: https://github.com/ifb/vapoursynth-colorbars

![image](https://user-images.githubusercontent.com/3579830/86949460-f62d5f80-c14e-11ea-8d05-27cf808d95b1.png)
The VS nnedi3 version is not affected

See avisynth issue https://github.com/jpsdr/NNEDI3/issues/9

https://forum.doom9.org/showthread.php?p=1917912#post1917912

**Comment by sekrit-twc** [comment]
This operation is not well-defined. It is not possible to deinterlace a 4:2:0 image that is not mod4.

**Comment by theChaosCoder** [comment]
So it's not really a bug then? [nnedi3](https://github.com/dubhater/vapoursynth-nnedi3) seems to handle it differently, it does not show any green line.

**Comment by sekrit-twc** [comment]
If so, it's by accident. If the chroma res is odd, you are effectively trying to read or write outside of the frame when you interpolate the "other" line.
