### ISSUE TITLE
missing graphengine sources

### ISSUE THREAD

**Issue by sl1pkn07** [sekrit-twc/znedi3#14]
Hi

sems graphengine is a new requeriment for build. but the sources is not in repository (and i only found this https://github.com/microsoft/GraphEngine, and seems is not the project used in this repo)

greetings

**Comment by JeremyMahieu** [comment]
You can use this repo for the time being. All the graphengine stuff has been reverted to the latest commit that doesn't have it.
This fork does work with Vapoursynth API v4.
https://github.com/JeremyMahieu/znedi3

**Comment by sl1pkn07** [comment]
@sekrit-twc sorry, but, ping?

greetings

**Comment by putnam** [comment]
Still no way to compile without rolling back to pre-graphengine source. Bumping in case author wants to contribute that code
