### ISSUE TITLE
Compilation failure on ubuntu trusty with gcc/g++ 4.8.4

### ISSUE THREAD

**Issue by grill02** [sekrit-twc/znedi3#6]
after copying files from the linked vsxx repo,i got this error

g++ -c  -std=c++1y -O2 -fPIC  -Iznedi3 -Ivsxx  vsznedi3/vsznedi3.cpp -o vsznedi3/vsznedi3.o
vsznedi3/vsznedi3.cpp: In member function ‘virtual std::pair<VSFilterMode, int> VSZNEDI3::init(const ConstPropertyMap&, const PropertyMap&, const vsxx::VapourCore&)’:
vsznedi3/vsznedi3.cpp:159:37: error: parameter declared ‘auto’
   auto propagate_if_set = [&](auto &dst, int val)
                                     ^
vsznedi3/vsznedi3.cpp: In lambda function:
vsznedi3/vsznedi3.cpp:162:5: error: ‘dst’ was not declared in this scope
     dst = static_cast<std::remove_reference_t<decltype(dst)>>(val);
     ^
vsznedi3/vsznedi3.cpp:162:23: error: expected type-specifier
     dst = static_cast<std::remove_reference_t<decltype(dst)>>(val);
                       ^
vsznedi3/vsznedi3.cpp:162:23: error: expected ‘>’
vsznedi3/vsznedi3.cpp:162:23: error: expected ‘(’
vsznedi3/vsznedi3.cpp:162:23: error: ‘remove_reference_t’ is not a member of ‘std’
vsznedi3/vsznedi3.cpp:162:47: error: expected primary-expression before ‘decltype’
     dst = static_cast<std::remove_reference_t<decltype(dst)>>(val);
                                               ^
vsznedi3/vsznedi3.cpp:162:47: error: expected ‘)’ before ‘decltype’
vsznedi3/vsznedi3.cpp:162:47: error: expected ‘;’ before ‘decltype’
vsznedi3/vsznedi3.cpp: In member function ‘virtual std::pair<VSFilterMode, int> VSZNEDI3::init(const ConstPropertyMap&, const PropertyMap&, const vsxx::VapourCore&)’:
vsznedi3/vsznedi3.cpp:182:88: error: no match for call to ‘(VSZNEDI3::init(const ConstPropertyMap&, const PropertyMap&, const vsxx::VapourCore&)::__lambda1) (znedi3_nsize_e&, int)’
   propagate_if_set(nnedi3_params.nsize, in.get_prop<int>("nsize", map::default_val(-1)));
                                                                                        ^
vsznedi3/vsznedi3.cpp:159:29: note: candidates are:
   auto propagate_if_set = [&](auto &dst, int val)
                             ^
vsznedi3/vsznedi3.cpp:182:88: note: void (*)(int) <conversion>
   propagate_if_set(nnedi3_params.nsize, in.get_prop<int>("nsize", map::default_val(-1)));
                                                                                        ^
vsznedi3/vsznedi3.cpp:182:88: note:   candidate expects 2 arguments, 3 provided
vsznedi3/vsznedi3.cpp:159:49: note: VSZNEDI3::init(const ConstPropertyMap&, const PropertyMap&, const vsxx::VapourCore&)::__lambda1
   auto propagate_if_set = [&](auto &dst, int val)
                                                 ^
vsznedi3/vsznedi3.cpp:159:49: note:   candidate expects 1 argument, 2 provided
vsznedi3/vsznedi3.cpp:183:84: error: no match for call to ‘(VSZNEDI3::init(const ConstPropertyMap&, const PropertyMap&, const vsxx::VapourCore&)::__lambda1) (znedi3_nns_e&, int)’
   propagate_if_set(nnedi3_params.nns, in.get_prop<int>("nns", map::default_val(-1)));
                                                                                    ^
vsznedi3/vsznedi3.cpp:159:29: note: candidates are:
   auto propagate_if_set = [&](auto &dst, int val)
                             ^
vsznedi3/vsznedi3.cpp:183:84: note: void (*)(int) <conversion>
   propagate_if_set(nnedi3_params.nns, in.get_prop<int>("nns", map::default_val(-1)));
                                                                                    ^
vsznedi3/vsznedi3.cpp:183:84: note:   candidate expects 2 arguments, 3 provided
vsznedi3/vsznedi3.cpp:159:49: note: VSZNEDI3::init(const ConstPropertyMap&, const PropertyMap&, const vsxx::VapourCore&)::__lambda1
   auto propagate_if_set = [&](auto &dst, int val)
                                                 ^
vsznedi3/vsznedi3.cpp:159:49: note:   candidate expects 1 argument, 2 provided
vsznedi3/vsznedi3.cpp:184:86: error: no match for call to ‘(VSZNEDI3::init(const ConstPropertyMap&, const PropertyMap&, const vsxx::Vapovsznedi3/vsznedi3.cpp:159:29: note: candidates are:
   auto propagate_if_set = [&](auto &dst, int val)
                             ^
vsznedi3/vsznedi3.cpp:198:89: note: void (*)(int) <conversion>
   propagate_if_set(nnedi3_params.slow_exp, in.get_prop<int>("exp", map::default_val(-1)));
                                                                                         ^
vsznedi3/vsznedi3.cpp:198:89: note:   candidate expects 2 arguments, 3 provided
vsznedi3/vsznedi3.cpp:159:49: note: VSZNEDI3::init(const ConstPropertyMap&, const PropertyMap&, const vsxx::VapourCore&)::__lambda1
   auto propagate_if_set = [&](auto &dst, int val)
                                                 ^
vsznedi3/vsznedi3.cpp:159:49: note:   candidate expects 1 argument, 2 provided
vsznedi3/vsznedi3.cpp:199:96: error: no match for call to ‘(VSZNEDI3::init(const ConstPropertyMap&, const PropertyMap&, const vsxx::VapourCore&)::__lambda1) (unsigned char&, int)’
   propagate_if_set(nnedi3_params.show_mask, in.get_prop<int>("show_mask", map::default_val(-1)));
                                                                                                ^
vsznedi3/vsznedi3.cpp:159:29: note: candidates are:
   auto propagate_if_set = [&](auto &dst, int val)
                             ^
vsznedi3/vsznedi3.cpp:199:96: note: void (*)(int) <conversion>
   propagate_if_set(nnedi3_params.show_mask, in.get_prop<int>("show_mask", map::default_val(-1)));
                                                                                                ^
vsznedi3/vsznedi3.cpp:199:96: note:   candidate expects 2 arguments, 3 provided
vsznedi3/vsznedi3.cpp:159:49: note: VSZNEDI3::init(const ConstPropertyMap&, const PropertyMap&, const vsxx::VapourCore&)::__lambda1
   auto propagate_if_set = [&](auto &dst, int val)
                                                 ^
vsznedi3/vsznedi3.cpp:159:49: note:   candidate expects 1 argument, 2 provided
make: *** [vsznedi3/vsznedi3.o] Error 1

Any Help is appreciated. I am new to posting here, so I might have omitted something.

**Comment by DJATOM** [comment]
GCC 4.8 is kinda old. Try never compiler from backports or find it somewhere in the Internet. Also you can compile gcc on your own.

**Comment by sekrit-twc** [comment]
Upgrade to GCC 5.

**Comment by grill02** [comment]
Thanks for the replies.

I upgraded gcc/g++ to 5.4, and compilation went flawlessly.

But when I tried to use it on a test video, I got a significant slowdown over vanilla nnedi3. The nnedi3.so is from the repo, https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth (package vapoursynth-extra-plugins). But I also compiled by own version of nnedi3 and the results were essentially the same.

On my laptop, opencl has only 1 device (cpu), and does not support GPU. I compiled nned3cl, and it gave essentially the same results as znedi3.

The test video is at http://www.dailymotion.com/video/x59rq9r . I downloaded the lowest quality version with youtube-dl, which is 176x108 h264 at 12.5 fps, and upscaled it by a factor of 4.

On my test video, with my setup, I got

NNEDI3: fps= 92  speed=7.37x
ZNEDI3: fps= 21  speed=1.64x

I have a 4 core laptop. Both nnedi3 and znedi3 use all 4 cores, i.e. cpu usage is 100% for both.

Some (maybe) relevant info:

$$ uname -a
Linux ani-HP-Notebook 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$$ lspci -nn|grep VGA
00:02.0 VGA compatible controller [0300]: Intel Corporation Broadwell-U Integrated Graphics [8086:1606] (rev 09)


The vspipe command was

vspipe --y4m test.vpy - | ffmpeg -hide_banner -loglevel info -f yuv4mpegpipe -i -  -c:v h264_vaapi -vf "format=nv12,hwupload"  -vaapi_device /dev/dri/card0 out.mkv -y

There was no special reason to use h264_vaapi, it just runs the fastest, so the speedup/slowdown would essentially be on account of vapoursynth and not ffmpeg.

I used edi_rpow2.py file from https://gist.github.com/YamashitaRen/020c497524e794779d9c, as mentioned in the help text. For testing with znedi, I changed core.nnedi3.nnedi3 to core.znedi3.nnedi3 in line 6.

My test.vpy looks like

-----

INFILE="Star Trek Enterprise - S01E04 - Strange New World-x59rq9r.mp4"

from vapoursynth import core
core.std.LoadPlugin('/home/ani/.python_script/vsznedi3.so')
from edi_rpow2 import nnedi3_rpow2

video = core.ffms2.Source(source=INFILE,cache=False)
video=nnedi3_rpow2(video, rfactor=4,nsize=0,nns=3,qual=1,pscrn=2,opt=True)
video.set_ouput()

------



$$ ldd vsznedi3.so 
  linux-vdso.so.1 =>  (0x00007ffefc15e000)
  libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f80e0fb6000)
  libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f80e0cb0000)
  libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f80e0a99000)
  libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f80e06d4000)
  /lib64/ld-linux-x86-64.so.2 (0x00007f80e14d9000)
----------

From the doom9 forum post, I understood that znedi3 is a CPU optimized version of nnedi3, so I did not expect it to be slower than nnedi3.

Am I doing something wrong, or are these expected results? Is there any rule of thumb of when znedi3 will run faster than nnedi3?

**Comment by sekrit-twc** [comment]
For best performance on x86, you need to enable x86 support. See the Makefile.

**Comment by grill02** [comment]
After compiling with
X86 enabled, the speed did increase. I also tried with -O3 in the Makefile instead of -O2.
With the same setup as above, I got:

(X86) ZNEDI3: fps= 50 speed=4.01x
(X86 X86_AVX512) ZNEDI3: fps= 53 speed=4.24x
(X86 X86_AVX512 -O3 ) ZNEDI3: fps= 53 speed=4.23x

While its still a bit slower compared to vanilla nnedi3, the speed is roughly comparable. I guess the slowdown might have something to do with the particular input file and/or my system specs.

Thanks to the owner for writing this code. I've become a big fan of nnedi3 since I started using it a little while ago. My only grouse is how slowly vapoursynth runs it on my machine. But I hope in the future I will be able to replace it with znedi3. Right now I encode the video I want to watch with the vspipe+ffmpeg setup. It uses 100% cpu, and still takes a while . Hopefully when znedi3 becomes faster, I can use mpv+vapoursynth so that upscaling can happen in real time as I'm watching the video.

**Comment by sekrit-twc** [comment]
znedi3 runs better on Skylake(-X) architecture, but it should still not be slower than nnedi3. You can build the  "testapp/testapp" target to debug the issue.

    make X86=1 testapp/testapp
    wget https://www.ece.rice.edu/~wakin/images/lena512color.tiff
    convert lena512color.tiff lena512color.bmp
    ./testapp/testapp --times 10 --cpu sse2 nnedi3_weights.bin lena512color.tiff /tmp/out.bmp
    ./testapp/testapp --times 10 --cpu avx nnedi3_weights.bin lena512color.tiff /tmp/out.bmp
    ./testapp/testapp --times 10 --cpu avx2 nnedi3_weights.bin lena512color.tiff /tmp/out.bmp

On 3.0 GHz Skylake (i7-6500U), I get 14 Mpx/s in AVX and 22 Mpx/s in AVX2. AVX2 throughput will be lower on Haswell/Broadwell, but the AVX throughput should be the same. If you observe similar Mpx/s scores, you must explain how you are measuring the speed.

**Comment by grill02** [comment]
It might be that my machine is just not new enough to make full use of znedi3.

-------------
make clean
make X86=1
make X86=1 testapp/testapp
convert lena512color.tiff lena512color.bmp
./testapp/testapp --times 10 --cpu $MY_CPU_TYPE nnedi3_weights.bin lena512color.bmp /tmp/out.bmp
-------------
with $MY_CPU_TYPE as below, Mpx/s are:
-------------
mmx: 0.517099
sse: 2.63776
sse2: 3.72383
sse3: 3.73643
ssse3: 3.6129
sse41: 3.69684
sse42: 3.70514

avx : Illegal instruction (core dumped)
f16c: Illegal instruction (core dumped)
avx2: Illegal instruction (core dumped)
avx512f: Illegal instruction (core dumped)
----------
Running the same command with 'sudo' produced no output (i.e. the program just exited)

Compilation went off cleanly, without any errors or warnings (make X86=1 testapp/testapp ). I dont really know anything about AVX or SSE(2/3/4) other than that they are supposed to be specialized instruction sets for getting arithmetic operations done faster.

For cpu type, 
$$grep -m 1 name /proc/cpuinfo
model name      : Intel(R) Pentium(R) CPU 3825U @ 1.90GHz

For cpu supported ops, note that sse2/3/4 is present, while avx/avx2 is not
$$cat /proc/cpuinfo |grep flags
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer xsave rdrand lahf_lm abm 3dnowprefetch ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust erms invpcid rdseed

Kernel version
$$uname -a
Linux ani-HP-Notebook 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$$gcc --version
gcc (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904
Copyright (C) 2015 Free Software Foundation, Inc.

This page (https://ark.intel.com/products/86348/Intel-Pentium-Processor-3825U-2M-Cache-1_90-GHz)  indicates that avx is not supported on this cpu, the best supported seems to be sse 4.1/4.2. On the other hand, this page (https://www.notebookcheck.net/Intel-Pentium-3825U-Notebook-Processor.139911.0.html) seems to indicate that avx is supported.

**Comment by sekrit-twc** [comment]
I see. I assumed you had a Core-series processor when your earlier comment mentioned Broadwell. Indeed, znedi3 may not match the performance of nnedi3 on SSE-only processors.

**Comment by grill02** [comment]
Hmm, too bad for me. But, as I said before, thanks for the code.

A few suggestions:

The only links that show up when searching for znedi3 are the doom9 forum post (whose title is somewhat incomplete since znedi3 is'nt mentioned at all) and the github repo. Ideally znedi3 should be mentioned here (http://www.vapoursynth.com/doc/pluginlist.html) since it is a major improvement over vanilla nnedi3. Also the doom9 post has a link to a windows dll. But it would be better/cleaner if there was an official release , atleast for windows/mac on the github page itself. It seems a pity to have written so much good code which so many potential users can find or don't know about.

Secondly, the readme.rst file (which shows up when one loads the github page via browser) is a direct copy of the nnedi3 file. However, there is no ./autogen.sh or ./configure included as part of znedi3. This might be a trivial thing for an expert, but might trip up an ordinary user who just wants to get znedi3 working on this machine. If a release were provided, this might not be so important.

Maybe the readme.rst could contain stuff about X86=1, the minimum compiler requirement, and the desired minimum system specs. When I first failed to  compile znedi3 a couple of weeks ago, I gave up for a while since I thought znedi was defunct (due to lack of search results) and I could'nt get the windows dll from doom9 working via wine (python 3.6/vapoursynth R40 fails wih wine, known bug). Only after the commit of Nov 29 did I realize it was still an active project. So a fix to readme.rst might prevent someone else from making my mistake.

Thirdly, when one checks out the repo via 'git clone' or even downloads the auto-generated zip file, the vsxx/ folder ends up empty. This causes another compile failure ('vsxx_pluginmain.h' not found). I am not sure why this is, but the vsxx repo seems to be 'linked', not not included directly. So I had to manually copy the files from here (https://github.com/sekrit-twc/vsxx/tree/21179602c988bfe5003f5b36a0e7f690fea23695). Again, this might be a small thing for experts, but not so great for an ordinary user.

Ideally, at some future time the nnedi3 developers should include the nnedi3cl and znedi3 code into their own project. That way support can be enabled/disabled at compile time depending on system/gpu specs to get the fastest nnedi3 implementation running. But that is a separate discussion.

**Comment by oyvindln** [comment]
@grill02 I also had to read and tinker a bit to get this to compile, so I made a PR to update the documentation at least.

ZNEDI3 is actually mentioned in the plugin list now, but the link goes to a forum thread about an OpenCL version of nnedi3 instead

**Comment by grill02** [comment]
Thanks!
