### ISSUE TITLE
avoiding file conficts with nnedi3_weights.bin from nnedi3

### ISSUE THREAD

**Issue by sl1pkn07** [sekrit-twc/znedi3#8]
Hi

nnedi3 store the nnedi3_weights.bin file into (one of the possible paths) /usr/share/nnedi3

and znedi3 use the same path.

is possible store the nnedi3_weights.bin into /usr/share/znedi3?

greetings

**Comment by sekrit-twc** [comment]
They're the same weights file, so it doesn't matter.

**Comment by sl1pkn07** [comment]
yes if use package from distro and try to install nnedi3 and znedi3 at same time. because one make conflict each other and cant install both in the same time because both packages ship the same file in the same path

**Comment by sekrit-twc** [comment]
Distro issue. Make a separate package for weights file or something.

**Comment by sl1pkn07** [comment]
yes. this i make now. but is better use other path. like nnedi3CL do
