### ISSUE TITLE
Error when using 32-bit float input clip

### ISSUE THREAD

**Issue by b6b** [sekrit-twc/znedi3#9]
Hi, I'm not able to run znedi3 with a 32-bit float clip. Calling `core.znedi3.nnedi3(clip,field=1)` results in  `vapoursynth.Error: znedi3: failed to create nnedi3`

**Comment by sekrit-twc** [comment]
Fixed in master.

**Comment by b6b** [comment]
@sekrit-twc Just got around to testing the latest master and the call still results in the same error.

The input clip is `YUV420PS32` if that helps at all. Also running vapoursynth r49 on arch linux. Happy to provide more details if needed.

**Comment by sekrit-twc** [comment]
It works for me:

    c = core.std.BlankClip(format=core.register_format(vs.YUV, vs.FLOAT, 32, 1, 1))
    c = core.znedi3.nnedi3(c, field=1)
    c.set_output()

Maybe you didn't actually build master?

**Comment by b6b** [comment]
Ah I'm dumb... Had an older version I compiled myself that was running over the AUR package :sweat_smile: 

All is good now. Thank you!
